CREATE TABLE `AIUTO`
(
    `ID`                          INT NOT NULL AUTO_INCREMENT,
    `TITOLO_MISURA`               LONGTEXT,
    `SOGGETTO_CONCEDENTE`         LONGTEXT,
    `COR`                         LONGTEXT,
    `TITOLO_PROGETTO`             LONGTEXT,
    `DATA_CONCESSIONE`            LONGTEXT,
    `CUP`                         LONGTEXT,
    `ATTO_CONCESSIONE`            LONGTEXT,
    `DENOMINAZIONE_BENEFICIARIO`  LONGTEXT,
    `CODICE_FISCALE_BENEFICIARIO` LONGTEXT,
    `ID_COMPONENTE_AIUTO`         LONGTEXT,
    `COD_PROCEDIMENTO`            LONGTEXT,
    `DES_PROCEDIMENTO`            LONGTEXT,
    `DES_REGOLAMENTO`             LONGTEXT,
    `DES_STRUMENTO`               LONGTEXT,
    `ELEMENTO_DI_AIUTO`           VARCHAR(255),
    `IMPORTO_NOMINALE`            VARCHAR(255),
    PRIMARY KEY (`ID`)
);